### ISSUE TITLE
Use Regex! Use git!

### ISSUE THREAD

**Issue by Killfrra** [mitko112/My-work-on-League-Sandbox#1]
It looks like you're editing scripts **by hand**, over the course of days, instead of using the bulk file replacement utility **once**. I'm the one responsible for the "Massive refactoring" commit and I didn't do it manually. And I do not advise you to do this, you are just wasting your time and it hurts me to look at it.
What's more, not only are you editing one file at a time, you're also uploading one file at a time, instead of editing them all and making **one** commit using git or a git plugin for IDE!

**Comment by mitko112** [comment]
I have already refactored all my scripts long time ago in my PC and now I am uploading them on GitHub by copy paste method.

**Comment by Killfrra** [comment]
OK. Then just **use git!**
Are these your scripts?
Are you on the discord on the LS developer server? If so, what nickname are you known by?

**Comment by Killfrra** [comment]
I'm sorry, I didn't find anything resembling private messages on github and any of your contacts, so I have to write here

**Comment by mitko112** [comment]
Yes Mine. I am Audi TT

**Comment by Killfrra** [comment]
:laughing: I'm 7abf7473. Long time no see you on our server

**Comment by mitko112** [comment]
I found a new way to upload them in bundles and not just rewriting them one by one.
